// как составляется sku:
// 1 цифра - номер категории,
// 2 цифры - номер товара из 4 цифр начиная с 0001
// итого: 10001 - джинсы первый товар

import { Size } from './generated/prisma/enums'

// платья 10001
// джинсы 20001
// топы 30001
// лонгсливы 40001
// нижнее белье 50001
// пижамы 60001
// спортивные костюмы 70001
// пальто 80001
// обувь 90001
// сумки и аксессуары 100001
// юбки 110001
// купальники 120001

export const colors = [
  { id: 1, name: 'Чёрный', hex: '#000000' },
  { id: 2, name: 'Белый', hex: '#F3EFE7' },
  { id: 3, name: 'Светло-серый', hex: '#E5E5E5' },
  { id: 4, name: 'Молочный', hex: '#FFFDD0' },
  { id: 5, name: 'Бежевый', hex: '#E6D5B8' },
  { id: 6, name: 'Кофейный', hex: '#B5937B' },
  { id: 7, name: 'Синий', hex: '#0B3C5D' },
  { id: 8, name: 'Голубой', hex: '#A7C7E7' },
  { id: 9, name: 'Зелёный', hex: '#3A7D44' },
  { id: 10, name: 'Оливковый', hex: '#7A8450' },
  { id: 11, name: 'Мятный', hex: '#A8E6CF' },
  { id: 12, name: 'Красный', hex: '#8B2D2D' },
  { id: 13, name: 'Бордовый', hex: '#5A1F2B' },
  { id: 14, name: 'Розовый', hex: '#E8A6B8' },
  { id: 15, name: 'Пыльная роза', hex: '#C48A9A' },
  { id: 16, name: 'Фиолетовый', hex: '#5B4B8A' },
]

export const categories = [
  { name: 'Платья', slug: 'dress' },
  { name: 'Джинсы и брюки', slug: 'jeans' },
  { name: 'Топы, майки и боди', slug: 'tops' },
  { name: 'Лонгсливы', slug: 'longsleeves' },
  { name: 'Нижнее белье', slug: 'underwear' },
  { name: 'Шелковые пижамы', slug: 'sleepwear' },
  { name: 'Спортивные костюмы', slug: 'sportwear' },
  { name: 'Пальто', slug: 'coat' },
  { name: 'Обувь', slug: 'shoes' },
  { name: 'Сумки и аксессуары', slug: 'bags' },
  { name: 'Юбки', slug: 'skirt' },
  { name: 'Купальники', slug: 'swimming' },
]

export const products = [
  // платья
  {
    sku: '10001',
    name: 'Платье Zarina',
    category: 'dress',
    price: 1100,
    oldPrice: 2100,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778921217/dress-10001-1_goq92x.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778921218/dress-10001-2_zna3at.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778921218/dress-10001-3_ebrscs.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778921218/dress-10001-4_d8pe0t.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 10 },
      { size: Size.XS, stock: 2 },
      { size: Size.S, stock: 1 },
      { size: Size.M, stock: 10 },
      { size: Size.L, stock: 11 },
    ],
    color: { id: 15, name: 'Пыльная роза', hex: '#C48A9A' },
    composition: 'нейлон 35%; вискоза 60%; спандекс 5%',
    sizeOnModel: '42', //размер на модели
    heightOnModel: '170', //рост модели
    country: 'China', //страна производства
    description:
      'Платье нарядное вечернее женское футляр с&nbsp;вырезом на&nbsp;груди из&nbsp;сетки&nbsp;&mdash; идеальный вариант для создания элегантного, эффектного женственного образа. Благодаря коротким рукавам, разрезу на&nbsp;спереди и&nbsp;кокетке декорированной сеткой платье идеально смотрится как на&nbsp;высоких женщинах, так и&nbsp;на&nbsp;женщинах среднего и&nbsp;невысокого роста.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Деликатная стирка',
  },
  {
    sku: '10002',
    name: 'Платье Miami Long Dress',
    category: 'dress',
    price: 2041,
    oldPrice: 7560,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922033/dress-10002-1_hnf251.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922033/dress-10002-2_k3smkk.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922034/dress-10002-3_i3eclq.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922034/dress-10002-4_fway9t.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 10 },
      { size: Size.XS, stock: 2 },
      { size: Size.S, stock: 1 },
      { size: Size.M, stock: 10 },
      { size: Size.L, stock: 11 },
    ],
    color: { id: 1, name: 'Чёрный', hex: '#000000' },
    composition: 'нейлон 35%; вискоза 60%; спандекс 5%',
    sizeOnModel: '42', //размер на модели
    heightOnModel: '170', //рост модели
    country: 'China', //страна производства
    description:
      'Платье нарядное вечернее женское футляр с&nbsp;вырезом на&nbsp;груди из&nbsp;сетки&nbsp;&mdash; идеальный вариант для создания элегантного, эффектного женственного образа. Благодаря коротким рукавам, разрезу на&nbsp;спереди и&nbsp;кокетке декорированной сеткой платье идеально смотрится как на&nbsp;высоких женщинах, так и&nbsp;на&nbsp;женщинах среднего и&nbsp;невысокого роста.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Деликатная стирка',
  },
  // джинсы
  {
    sku: '20001',
    name: 'Джинсы Zarina',
    category: 'jeans',
    price: 4050,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922125/jeans-20001_vpt5bb.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922125/jeans-20002_raa8yd.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922126/jeans-20003_et9v7p.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922127/jeans-20004_ofguzi.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 10 },
      { size: Size.XS, stock: 2 },
      { size: Size.S, stock: 1 },
      { size: Size.M, stock: 10 },
      { size: Size.L, stock: 11 },
    ],
    color: { id: 1, name: 'Светло-серый', hex: '#E5E5E5' },
    composition: 'нейлон 35%; вискоза 60%; спандекс 5%',
    sizeOnModel: '40',
    heightOnModel: '170',
    country: 'China',
    description:
      'Платье нарядное вечернее женское футляр с&nbsp;вырезом на&nbsp;груди из&nbsp;сетки&nbsp;&mdash; идеальный вариант для создания элегантного, эффектного женственного образа. Благодаря коротким рукавам, разрезу на&nbsp;спереди и&nbsp;кокетке декорированной сеткой платье идеально смотрится как на&nbsp;высоких женщинах, так и&nbsp;на&nbsp;женщинах среднего и&nbsp;невысокого роста.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Деликатная стирка',
  },
  {
    sku: '20002',
    name: 'Джинсы Slim Fit',
    category: 'jeans',
    price: 4290,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922201/jeans-20002-1_wexje1.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922201/jeans-20002-2_zf2iw4.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 5 },
      { size: Size.XS, stock: 8 },
      { size: Size.S, stock: 15 },
      { size: Size.M, stock: 12 },
      { size: Size.L, stock: 7 },
    ],
    color: { id: 7, name: 'Синий', hex: '#0B3C5D' },
    composition: 'хлопок 98%; эластан 2%',
    sizeOnModel: '36',
    heightOnModel: '172',
    country: 'Turkey',
    description:
      'Классические джинсы Slim Fit с эффектом потертости. Идеально сидят по фигуре, визуально вытягивают силуэт. Универсальная модель, которая подойдет для повседневной носки и офисного стиля.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Стирать при температуре не выше 30°C, не отбеливать, гладить при средней температуре',
  },
  {
    sku: '20003',
    name: 'Джинсы Boyfriend',
    category: 'jeans',
    price: 4590,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922253/jeans-20003-1_mv2cmk.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922254/jeans-20003-2_hnpg7e.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 3 },
      { size: Size.XS, stock: 5 },
      { size: Size.S, stock: 12 },
      { size: Size.M, stock: 10 },
      { size: Size.L, stock: 8 },
    ],
    color: { id: 8, name: 'Голубой', hex: '#A7C7E7' },
    composition: 'хлопок 100%',
    sizeOnModel: '38',
    heightOnModel: '165',
    country: 'Italy',
    description:
      'Модные джинсы свободного кроя Boyfriend. Удобная модель с заниженной талией и потертостями на коленях. Отлично сочетаются с кедами и объемными свитерами.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Стирать при температуре 30°C, не отбеливать, сушить в расправленном виде',
  },
  {
    sku: '20004',
    name: 'Джинсы Wide Leg',
    category: 'jeans',
    price: 4890,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922287/jeans-20004-1_jf1m9v.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922288/jeans-20004-2_h4h7fj.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922290/jeans-20004-3_vypwoj.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922291/jeans-20004-4_tjb5vc.webp',
    ],
    sizes: [
      { size: Size.XS, stock: 7 },
      { size: Size.S, stock: 14 },
      { size: Size.M, stock: 12 },
      { size: Size.L, stock: 9 },
    ],
    color: { id: 1, name: 'Чёрный', hex: '#000000' },
    composition: 'хлопок 97%; эластан 3%',
    sizeOnModel: '36',
    heightOnModel: '175',
    country: 'Vietnam',
    description:
      'Стильные джинсы Wide Leg с высокой посадкой. Широкие штанины создают элегантный силуэт, визуально удлиняют ноги. Идеальный выбор для создания модного образа в стиле 90-х.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Деликатная стирка, не выкручивать, не отбеливать',
  },
  {
    sku: '20005',
    name: 'Джинсы с высокой талией',
    category: 'jeans',
    price: 4350,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922337/jeans-gray1_ph3j2v.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922337/jeans-gray1_ph3j2v.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922339/jeans-gray3_ywwaze.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922341/jeans-gray4_sgk8mn.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 4 },
      { size: Size.XS, stock: 6 },
      { size: Size.S, stock: 10 },
      { size: Size.M, stock: 8 },
      { size: Size.L, stock: 6 },
    ],
    color: { id: 3, name: 'Светло-серый', hex: '#E5E5E5' },
    composition: 'хлопок 99%; эластан 1%',
    sizeOnModel: '36',
    heightOnModel: '168',
    country: 'Bangladesh',
    description:
      'Классические джинсы с высокой талией. Модель подчеркивает талию и создает идеальные пропорции. Универсальный вариант для любого гардероба, подходит для офиса и повседневной носки.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Машинная стирка 30°C, не гладить по декоративным элементам',
  },
  // топы
  {
    sku: '30001',
    name: 'Charo Ibiza 1989',
    category: 'tops',
    price: 1490,
    oldPrice: 3499,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922390/jeans-embroidery-1_parpdl.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922390/jeans-embroidery-2_qbihb1.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922390/jeans-embroidery-4_fmqvng.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778922390/jeans-embroidery-3_efiv1o.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 2 },
      { size: Size.XS, stock: 4 },
      { size: Size.S, stock: 8 },
      { size: Size.M, stock: 7 },
      { size: Size.L, stock: 5 },
    ],
    color: { id: 5, name: 'Бежевый', hex: '#E6D5B8' },
    composition: 'хлопок 100%',
    sizeOnModel: '36',
    heightOnModel: '168',
    country: 'Portugal',
    description:
      'Уникальный дизайн и высокое качество материалов. Идеальный выбор для тех, кто хочет выделиться из толпы.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Ручная стирка при 30°C, не выжимать, сушить в горизонтальном положении',
  },
  {
    sku: '30002',
    name: 'Базовый топ с открытыми плечами',
    category: 'tops',
    price: 1890,
    oldPrice: 2990,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778923939/tops-offshoulder-1_cvfh6k.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778923940/tops-offshoulder-2_utzpng.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 5 },
      { size: Size.XS, stock: 8 },
      { size: Size.S, stock: 12 },
      { size: Size.M, stock: 10 },
      { size: Size.L, stock: 6 },
    ],
    color: { id: 2, name: 'Белый', hex: '#F3EFE7' },
    composition: 'вискоза 95%; эластан 5%',
    sizeOnModel: '38',
    heightOnModel: '170',
    country: 'Turkey',
    description:
      'Элегантный топ с открытыми плечами на резинке. Модель с короткими рукавами и воланами по низу. Идеально подходит для романтических свиданий и летних прогулок.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Деликатная стирка при 30°C, не отбеливать',
  },
  //лонгсливы
  {
    sku: '40001',
    name: 'Лонгслив с принтом',
    category: 'longsleeves',
    price: 1990,
    oldPrice: 3290,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778923984/longsleeve-print-1_mrljsn.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778923984/longsleeve-print-2_lyebex.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778923984/longsleeve-print-3_t0i417.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778923984/longsleeve-print-4_n3ganx.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 3 },
      { size: Size.XS, stock: 6 },
      { size: Size.S, stock: 10 },
      { size: Size.M, stock: 8 },
      { size: Size.L, stock: 4 },
    ],
    color: { id: 7, name: 'Синий', hex: '#0B3C5D' },
    composition: 'хлопок 85%; полиэстер 15%',
    sizeOnModel: '36',
    heightOnModel: '172',
    country: 'Bangladesh',
    description:
      'Уютный лонгслив с ярким принтом. Модель свободного кроя с круглым вырезом. Отлично сочетается с джинсами и юбками для повседневного образа.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Стирать при 30°C, гладить с изнанки',
  },
  {
    sku: '40002',
    name: 'Лонгслив с высоким горлом',
    category: 'longsleeves',
    price: 2290,
    oldPrice: 3990,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924046/longsleeve-turtleneck-1_yctztn.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924047/longsleeve-turtleneck-2_xkhlul.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924047/longsleeve-turtleneck-4_i7cepm.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924047/longsleeve-turtleneck-3_vqblap.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 4 },
      { size: Size.XS, stock: 7 },
      { size: Size.S, stock: 12 },
      { size: Size.M, stock: 9 },
      { size: Size.L, stock: 5 },
    ],
    color: { id: 5, name: 'Бежевый', hex: '#E6D5B8' },
    composition: 'кашемир 10%; шерсть 50%; полиэстер 40%',
    sizeOnModel: '36',
    heightOnModel: '168',
    country: 'Italy',
    description:
      'Элегантный лонгслив с высоким горлом. Теплая и мягкая модель, идеально подходит для холодного сезона. Отлично смотрится с пальто и пиджаками.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Химчистка или деликатная стирка',
  },
  {
    sku: '40003',
    name: 'Лонгслив PRADA',
    category: 'longsleeves',
    price: 12290,
    oldPrice: 23990,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924251/longsleev-black1_wljpsi.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924251/longsleev-black2_fklein.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924252/longsleev-black3_s4rgek.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924254/longsleev-black4_kkbvi9.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 10 },
      { size: Size.XS, stock: 7 },
      { size: Size.S, stock: 12 },
      { size: Size.M, stock: 9 },
      { size: Size.L, stock: 5 },
    ],
    color: { id: 1, name: 'Чёрный', hex: '#000000' },
    composition: 'кашемир 10%; шерсть 50%; полиэстер 40%',
    sizeOnModel: '36',
    heightOnModel: '168',
    country: 'Italy',
    description:
      'Элегантный лонгслив с высоким горлом. Теплая и мягкая модель, идеально подходит для холодного сезона. Отлично смотрится с пальто и пиджаками.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Химчистка или деликатная стирка',
  },
  // нижнее белье
  {
    sku: '50001',
    name: 'Бюстгальтер с кружевом',
    category: 'underwear',
    price: 1490,
    oldPrice: 2490,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924295/bra-lace-1_f6eu03.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924295/bra-lace-2_surqht.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924296/bra-lace-3_vxow6z.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924298/bra-lace-4_rffuai.webp',
    ],
    sizes: [
      { size: Size.XS, stock: 5 },
      { size: Size.S, stock: 8 },
      { size: Size.M, stock: 7 },
      { size: Size.L, stock: 4 },
    ],
    color: { id: 1, name: 'Чёрный', hex: '#000000' },
    composition: 'полиамид 85%; эластан 15%',
    sizeOnModel: 'M',
    heightOnModel: '170',
    country: 'China',
    description:
      'Красивый бюстгальтер из кружева. Удобная модель на тонких регулируемых бретелях. Идеальный выбор для создания романтичного образа.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Ручная стирка, не отбеливать',
  },
  {
    sku: '50002',
    name: 'Трусы слипы хлопковые',
    category: 'underwear',
    price: 890,
    oldPrice: 1490,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924357/panties-cotton-1_qyi412.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924357/panties-cotton-2_f3vc3v.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924358/panties-cotton-3_hrc6yj.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924360/panties-cotton-4_j5iaxv.webp',
    ],
    sizes: [
      { size: Size.XS, stock: 10 },
      { size: Size.S, stock: 15 },
      { size: Size.M, stock: 12 },
      { size: Size.L, stock: 8 },
    ],
    color: { id: 12, name: 'Красный', hex: '#8B2D2D' },
    composition: 'хлопок 95%; эластан 5%',
    sizeOnModel: 'S',
    heightOnModel: '168',
    country: 'Turkey',
    description:
      'Удобные хлопковые трусы слипы. Мягкий материал, идеально подходит для повседневной носки. Гипоаллергенно и дышащее.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Стирать при 40°C, не отбеливать',
  },
  // пижамы
  {
    sku: '60001',
    name: 'Шелковая пижама классическая',
    category: 'sleepwear',
    price: 8990,
    oldPrice: 14990,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924401/pajamas-silk-1_r7cute.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924401/pajamas-silk-2_jh6rlc.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924402/pajamas-silk-3_appxfw.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924404/pajamas-silk-4_kmu1ki.webp',
    ],
    sizes: [
      { size: Size.XS, stock: 3 },
      { size: Size.S, stock: 5 },
      { size: Size.M, stock: 4 },
      { size: Size.L, stock: 2 },
    ],
    color: { id: 5, name: 'Бежевый', hex: '#E6D5B8' },
    composition: 'шелк 100%',
    sizeOnModel: 'S',
    heightOnModel: '170',
    country: 'Italy',
    description:
      'Роскошная пижама из натурального шелка. Комплект состоит из рубашки с отложным воротником и длинных брюк. Идеальный выбор для комфортного сна и уютных вечеров.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Химчистка или ручная стирка',
  },
  {
    sku: '60002',
    name: 'Пижама шелковая с кружевом',
    category: 'sleepwear',
    price: 10990,
    oldPrice: 16990,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924457/pajamas-lace-1_ax9ssn.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924457/pajamas-lace-2_vytttl.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924459/pajamas-lace-3_pifzzg.webp',
    ],
    sizes: [
      { size: Size.XS, stock: 2 },
      { size: Size.S, stock: 4 },
      { size: Size.M, stock: 3 },
      { size: Size.L, stock: 1 },
    ],
    color: { id: 1, name: 'Чёрный', hex: '#000000' },
    composition: 'шелк 95%; кружево 5%',
    sizeOnModel: 'S',
    heightOnModel: '172',
    country: 'France',
    description:
      'Элегантная шелковая пижама с кружевной отделкой. Состоит из топа на тонких бретелях и шорт. Идеально для особых моментов и романтических вечеров.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Деликатная стирка при 30°C',
  },
  // спортивные костюмы
  {
    sku: '70001',
    name: 'Спортивный костюм с логотипом',
    category: 'sportwear',
    price: 4990,
    oldPrice: 7990,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924492/sportswear-logo-1_mnlj5d.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924493/sportswear-logo-2_fdar20.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924493/sportswear-logo-2_fdar20.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 3 },
      { size: Size.XS, stock: 5 },
      { size: Size.S, stock: 8 },
      { size: Size.M, stock: 7 },
      { size: Size.L, stock: 4 },
    ],
    color: { id: 5, name: 'Бежевый', hex: '#E6D5B8' },
    composition: 'хлопок 70%; полиэстер 30%',
    sizeOnModel: '36',
    heightOnModel: '168',
    country: 'Vietnam',
    description:
      'Удобный спортивный костюм из мягкого футера. Состоит из худи с капюшоном и штанов на манжетах. Идеально для тренировок и повседневной носки.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Стирать при 30°C, не отбеливать',
  },
  {
    sku: '70002',
    name: 'Спортивный костюм неоновый',
    category: 'sportwear',
    price: 5990,
    oldPrice: 8990,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924538/sportswear-neon-1_i3dvva.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924538/sportswear-neon-2_ffcuz8.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924541/sportswear-neon-3_ktmrwj.webp',
    ],
    sizes: [
      { size: Size.XS, stock: 4 },
      { size: Size.S, stock: 6 },
      { size: Size.M, stock: 5 },
      { size: Size.L, stock: 3 },
    ],
    color: { id: 14, name: 'Розовый', hex: '#E8A6B8' },
    composition: 'полиэстер 100%',
    sizeOnModel: '38',
    heightOnModel: '170',
    country: 'China',
    description:
      'Яркий спортивный костюм из дышащей ткани. Состоит из олимпийки на молнии и леггинсов. Идеально для бега и активных тренировок.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Машинная стирка 40°C, не гладить',
  },
  // пальто 80001
  {
    sku: '80001',
    name: 'Пальто шерстяное классическое',
    category: 'coat',
    price: 12990,
    oldPrice: 19990,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924582/coat-wool-1_afgb6y.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924583/coat-wool-2_afmikv.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924585/coat-wool-3_uxr1oy.webp',
    ],
    sizes: [
      { size: Size.XS, stock: 3 },
      { size: Size.S, stock: 5 },
      { size: Size.M, stock: 4 },
      { size: Size.L, stock: 2 },
    ],
    color: { id: 13, name: 'Бордовый', hex: '#5A1F2B' },
    composition: 'шерсть 80%; кашемир 20%',
    sizeOnModel: '36',
    heightOnModel: '172',
    country: 'Italy',
    description:
      'Элегантное пальто из мягкой шерсти с добавлением кашемира. Прямой крой, лацканы, два кармана. Идеально для офисного стиля и повседневных выходов.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Химчистка',
  },
  {
    sku: '80002',
    name: 'Пальто-оверсайз',
    category: 'coat',
    price: 14990,
    oldPrice: 22990,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924611/coat-oversize-1_ovsq4s.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924612/coat-oversize-2_s345tr.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924614/coat-oversize-3_bbfml6.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924615/coat-oversize-4_eamotk.webp',
    ],
    sizes: [
      { size: Size.XS, stock: 2 },
      { size: Size.S, stock: 4 },
      { size: Size.M, stock: 3 },
      { size: Size.L, stock: 1 },
    ],
    color: { id: 1, name: 'Чёрный', hex: '#000000' },
    composition: 'шерсть 70%; полиэстер 30%',
    sizeOnModel: '38',
    heightOnModel: '170',
    country: 'Turkey',
    description:
      'Модное пальто-оверсайз свободного кроя. Широкие рукава, глубокий карман, пояс на талии. Создает стильный и расслабленный образ.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Химчистка',
  },
  // обувь 90001 shoes
  {
    sku: '90001',
    name: 'Кеды белые',
    category: 'shoes',
    price: 3990,
    oldPrice: 5990,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924662/shoes-sneakers-1_zdxxce.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924663/shoes-sneakers-2_b0j2ug.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924665/shoes-sneakers-3_s4rik8.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 5 },
      { size: Size.XS, stock: 8 },
      { size: Size.S, stock: 12 },
      { size: Size.M, stock: 10 },
      { size: Size.L, stock: 6 },
    ],
    color: { id: 2, name: 'Белый', hex: '#F3EFE7' },
    composition: 'текстиль 60%; кожа 40%',
    sizeOnModel: '37',
    heightOnModel: '168',
    country: 'Vietnam',
    description:
      'Универсальные белые кроссовки на толстой подошве. Модель из комбинированных материалов, подходит для повседневной носки и прогулок.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Чистить влажной губкой',
  },
  {
    sku: '90002',
    name: 'Ботильоны на каблуке',
    category: 'shoes',
    price: 7990,
    oldPrice: 11990,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924657/shoes-booties-2_bcclwy.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924657/shoes-booties-1_mrd0ot.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 3 },
      { size: Size.XS, stock: 5 },
      { size: Size.S, stock: 7 },
      { size: Size.M, stock: 6 },
      { size: Size.L, stock: 4 },
    ],
    color: { id: 5, name: 'Бежевый', hex: '#E6D5B8' },
    composition: 'натуральная кожа 100%',
    sizeOnModel: '38',
    heightOnModel: '170',
    country: 'Portugal',
    description:
      'Элегантные ботильоны на устойчивом каблуке 8 см. Острая носочка, боковая молния. Идеально подходят для офиса и вечерних выходов.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Уход специальными средствами для кожи',
  },
  // сумки и аксессуары 100001 bags
  {
    sku: '100001',
    name: 'Сумка шоппер',
    category: 'bags',
    price: 2990,
    oldPrice: 4990,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924730/bag-shopper-1_mkcdp4.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924731/bag-shopper-2_a3lwb7.webp',
    ],
    sizes: [{ size: Size.ONESIZE, stock: 5 }],
    color: { id: 6, name: 'Кофейный', hex: '#B5937B' },
    composition: 'экокожа 100%',
    sizeOnModel: 'One size',
    heightOnModel: '170',
    country: 'India',
    description:
      'Просторная сумка-шоппер из качественной экокожи. Вместительная модель с длинными ручками. Идеально для покупок и повседневной носки.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Протирать влажной салфеткой',
  },
  {
    sku: '100002',
    name: 'Ремень кожаный',
    category: 'bags',
    price: 1490,
    oldPrice: 2490,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924734/belt-leather-1_hvlubv.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924736/belt-leather-2_ycj2ds.webp',
    ],
    sizes: [{ size: Size.ONESIZE, stock: 10 }],
    color: { id: 1, name: 'Чёрный', hex: '#000000' },
    composition: 'натуральная кожа 100%',
    sizeOnModel: 'M',
    heightOnModel: '168',
    country: 'Italy',
    description:
      'Классический кожаный ремень с металлической пряжкой. Универсальный аксессуар, подходит для джинсов, брюк и платьев.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Уход специальными средствами для кожи',
  },
  // юбки 110001 skirt
  {
    sku: '110001',
    name: 'Юбка миди плиссированная',
    category: 'skirt',
    price: 3290,
    oldPrice: 4990,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924791/skirt-pleated-1_nrabq8.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924792/skirt-pleated-2_f014ik.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 4 },
      { size: Size.XS, stock: 6 },
      { size: Size.S, stock: 10 },
      { size: Size.M, stock: 8 },
      { size: Size.L, stock: 5 },
    ],
    color: { id: 4, name: 'Фиолетовый', hex: '#5B4B8A' },
    composition: 'полиэстер 100%',
    sizeOnModel: '36',
    heightOnModel: '172',
    country: 'China',
    description:
      'Стильная плиссированная юбка миди. Модель на широком поясе, идеально держит форму. Подходит для вечерних выходов и офиса.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Деликатная стирка, не гладить',
  },
  {
    sku: '110002',
    name: 'Юбка джинсовая',
    category: 'skirt',
    price: 2590,
    oldPrice: 3990,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924782/skirt-denim-1_ypbzy3.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924783/skirt-denim-2_qmwklz.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924788/skirt-denim-3_ppwqs9.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924789/skirt-denim-4_evidfp.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 5 },
      { size: Size.XS, stock: 7 },
      { size: Size.S, stock: 12 },
      { size: Size.M, stock: 9 },
      { size: Size.L, stock: 6 },
    ],
    color: { id: 11, name: 'Мятный', hex: '#A8E6CF' },
    composition: 'хлопок 98%; эластан 2%',
    sizeOnModel: '38',
    heightOnModel: '168',
    country: 'Turkey',
    description:
      'Модная джинсовая юбка длины миди. Модель на пуговицах, с карманами и эффектом потертостей. Идеально для повседневного образа.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Стирать при 30°C, не отбеливать',
  },
  // купальники 120001 swimming
  {
    sku: '120001',
    name: 'Купальник раздельный',
    category: 'swimming',
    price: 3990,
    oldPrice: 5990,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924847/swimsuit-bikini-1_yjttif.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924849/swimsuit-bikini-2_kvb3mz.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924907/swimsuit-bikini-3_peszy5.webp',
    ],
    sizes: [
      { size: Size.XS, stock: 4 },
      { size: Size.S, stock: 6 },
      { size: Size.M, stock: 5 },
      { size: Size.L, stock: 3 },
    ],
    color: { id: 10, name: 'Оливковый', hex: '#7A8450' },
    composition: 'полиамид 80%; эластан 20%',
    sizeOnModel: 'S',
    heightOnModel: '170',
    country: 'China',
    description:
      'Стильный раздельный купальник с анималистичным принтом. Лиф на косточках, плавки-бразилиана. Идеально для пляжного сезона.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Прополоскать после купания в соленой воде',
  },
  {
    sku: '120002',
    name: 'Купальник слитный',
    category: 'swimming',
    price: 4590,
    oldPrice: 6990,
    images: [
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924909/swimsuit-one-piece-1_c25ng8.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924911/swimsuit-one-piece-2_ltlqze.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924912/swimsuit-one-piece-3_virwuz.webp',
      'https://res.cloudinary.com/dkni6have/image/upload/v1778924914/swimsuit-one-piece-4_l8wggg.webp',
    ],
    sizes: [
      { size: Size.XXS, stock: 3 },
      { size: Size.XS, stock: 5 },
      { size: Size.S, stock: 7 },
      { size: Size.M, stock: 6 },
      { size: Size.L, stock: 4 },
    ],
    color: { id: 8, name: 'Голубой', hex: '#A7C7E7' },
    composition: 'полиамид 85%; эластан 15%',
    sizeOnModel: '36',
    heightOnModel: '168',
    country: 'Vietnam',
    description:
      'Элегантный слитный купальник с вырезом на спине. Модель утягивает фигуру, создавая идеальный силуэт. Подходит для активного отдыха на пляже.',
    delivery: 'Доставка бесплатно',
    refund: '14 дней на возврат',
    care: 'Ручная стирка, не отбеливать',
  },
]
